### ISSUE TITLE
In-line examples

### ISSUE THREAD

**Issue by cabo** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#136]
Apart from an appendix with examples, let's have in-line examples

**Comment by glyn** [comment]
To do list:

- [ ] Root selector
- [ ] Dot selector
- [ ] Dot wild card selector
- [ ] Index selector
- [ ] Index wild card selector
- [ ] Array slice selector
- [ ] Descendant selector
- [ ] List selector
- [ ] Filter selector
- [ ] Normalized paths

**Comment by goessner** [comment]
where should examples go in the meantime ?

**Comment by cabo** [comment]
I'd say:

ideas: right here

full proposals: PRs

**Comment by glyn** [comment]
Yes, drop examples in here and I'll try to include them in PRs. The only problem will be if an example turns out to generate a lot of discussion, as issues aren't great at threading. But let's cross that bridge when we get to it...

Or feel free to submit PRs. :-)

**Comment by goessner** [comment]
Format could be something like that ...

### `descendent-selector` 

| JSON | Query | Result | Comment| 
| --- | --- | --- | --- |
| `{ "o": {"key":7}}` | `$..o` | `$['o']` | Child node  |
|  | `$..['key']` | `$['o']`<br>`$['o']['key']` | Descendent node  | 
|  | `$..*` | `$['o']`<br>`$['o']['key']` |All descendent nodes  | 
|  | `$..[*]` | `$['o']`<br>`$['o']['key']` |All descendent nodes  | 

What's about invalid queries? Should they be mixed in or in a separate table / section ?

**Comment by glyn** [comment]
I quite like that format. Thanks! I anticipate each selector having three sections: "Syntax", "Semantics", and "Examples". It should be pretty obvious that the examples are non-normative without saying so every time.

It seems more manageable and readable to have the JSON document available alongside the examples rather than having to "jump around" the spec, even if this does lead to some duplication.

I like showing the result as Normalized Paths rather than values, since the former are unambiguous in the presence of duplicate values. I wonder if readers will be as comfortable? I guess they'll soon get the hang of it.

**Comment by goessner** [comment]
Thanks ... I will be back here earliest on Sunday ...

**Comment by glyn** [comment]
Inline examples are now complete.
