### ISSUE TITLE
About function

### ISSUE THREAD

**Issue by yangbodong22011** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#160]
Functions can be invoked at the tail end of a path - the input to a function is the output of the path expression. The function output is dictated by the function itself.

Refer：https://github.com/json-path/JsonPath#functions

**Comment by gregsdennis** [comment]
Thank you for this.  This is one possibility for a syntax for functions.  There are others, e.g. the common syntax `foo(param1, param2, ...)`.

We will need to compare all options before we make a decision.

**Comment by yangbodong22011** [comment]
@gregsdennis Yes, MongoDB operator is also a good choice: https://docs.mongodb.com/manual/reference/operator/query/

**Comment by danielaparker** [comment]
> Functions can be invoked at the tail end of a path - the input to a function is the output of the path expression. The function output is dictated by the function itself.
> 
> Refer：https://github.com/json-path/JsonPath#functions

Many, perhaps most, JSONPath implementations support functions in one form or another, in some cases only in filter expressions, in other cases both in and outside of filter expressions. The former generally restrict JSONPath to selecting elements in the original document only, the latter permit results that are computations performed on the original document.

(1) Implementations that use JavaScript (or Python or PHP) for evaluating JSONPath filter expressions, including original JavaScript Goessner, have access to all the JavaScript (or Python or PHP) functions. For example, they have access to functions that return the Unicode Normalization Form of strings, see [JavaScript String.prototype.normalize](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize) (or [Python unicodedata.normalize](https://docs.python.org/3.6/library/unicodedata.html#unicodedata.normalize) or [PHP normalizer.normalize](https://www.php.net/manual/en/normalizer.normalize.php)).

(2) The important and influential [Jayway implementation](https://github.com/json-path/JsonPath) introduced functions that can be invoked at the tail end of the path, as you mentioned. These can be used to return results that are computations performed on the original document.

(3) A couple of implementations that made up their own filter expression languages support function syntax like
```
$.books[?(tokenize(@.author,'\\s+')[-1] == 'Tolkien')]
```
see e.g. [here](https://danielaparker.github.io/JsonCons.Net/articles/JsonPath/JsonConsJsonPath.html#functions).

**Comment by gregsdennis** [comment]
***NOTE** I definitely think support for functions should **not** be part of the initial release but should be reserved for follow-up releases.*

I would like to propose the typical syntax for functions:

```
function_name([param list])
```

- A function name MUST be a string that starts with an alpha char and is followed by any number of alpha-numeric chars and underscores (same character set as `.`-syntax property names).  This should make them easily identifiable in expressions.
- A function MUST have parentheses, even if there are no parameters.
- The parameter list MUST be comma-delimited.  Each parameter may be any valid JSON Path expression, including the constant values that are allowed, e.g. booleans, numbers, etc, but not structured values (unless those are supported by the time functions are implemented).
- A function MUST return a value.

I would also suggest that parameters have an _expected_ type.  If the function receives a value for a parameter that is the wrong type, it should return `false` or some other "negative"-indicating value, much like the existence test.

### Predefined functions to start

#### `length(x)`

Receives any valid JSON Path, probably most commonly `@`, and returns the object or array length of the value at that location.

Optional support:

- non-singular paths - the return value would be the number of results returned by the path.
- string values - the return value would be the string length (probably unicode chars, not byte count)

#### `index()`

Receives no parameters and returns the index / property name of the current item (`@`).  I see no value in attempting to get the key of a specified path.

**Comment by danielaparker** [comment]
> _**NOTE** I definitely think support for functions should **not** be part of the initial release but should be considered for follow-up releases._
> 
Follow up _releases_, in the plural? Wouldn't that negate the primary benefit of an RFC, which is interoperability? 

> Each parameter may be any valid JSON Path expression, including the constant values that are allowed, e.g. booleans, numbers, etc, but not structured values (unless those are supported by the time functions are implemented).

I understand that in the draft it's currently underspecified what JSONPath expressions can evaluate to, but you're not suggesting that they can't evaluate to JSON arrays and objects in any context, are you? Also, if they can evaluate to `undefined`,  as has been proposed, that needs to be part of the type system supported by functions.

> #### `index()`
> Receives no parameters and returns the index / property name of the current item (`@`). 
> 
That doesn't sound like a function, as conventionally understood. Presumably it would need to receive a 'this' or 'self' parameter to access the "current item". Which would also require an extension to the type system needed to support functions.

**Comment by gregsdennis** [comment]
> Follow up releases, in the plural?

I don't understand what you're getting at.  I sincerely expect there to be revisions to this document after initial publication.  Why wouldn't there be?  Surely we would want to expand on the feature set.  Otherwise, the spec would never be published.

> Wouldn't that negate the primary benefit of an RFC, which is interoperability?

How does an RFC imply interoperability?

How does this feature (or multiple versioned releases, maybe?) negate interoperability?  If the spec defines functions, then any implementation of that spec, regardless of language/framework, would also be required to support them as defined.  That's interoperability.

> ... but you're not suggesting that they can't evaluate to JSON arrays and objects in any context, are you?

No, I'm not suggested that.  They can definitely evaluate to arrays and objects.  Any valid value should be able to be passed to a function, but if a function receives a value of a type it's not expecting, it should return a negative result of some kind.  This aligns with the current idea that if a path parses correctly, it should not throw errors upon evaluation.

> if they can evaluate to `undefined`, as has been proposed, that needs to be part of the type system supported by functions.

Yeah.

> That doesn't sound like a function, as conventionally understood.

Why not?  Parameterless functions exist.  I considered using `index(@)`, but then it only makes sense for the parameter to be `@`, so why have it at all?  Not having a parameter means that someone couldn't do `index(@.foo)`, which is a pointless function because it just returns `"foo"`.  Making this a parameterless function makes it hard for users to do things they're not allowed to do or don't make sense.  It already knows that its context is the current item (and the item's parent).  (Presumably, the implementation is iterating through the items in a loop and has access to these things, at which point it can pass that context to whatever implementation it has internally.)

**Comment by danielaparker** [comment]
> > That doesn't sound like a function, as conventionally understood.
> 
> Why not? Parameterless functions exist.

Can you provide an example? I think a parameter-less function must return a constant.

 > I considered using `index(@)`, 

I don't think that works, if you want `index` to be considered a function like any other. Within a JSONPath expression, a bare `@` evaluates to a value, a value that does not carry with it any information about the array index or object member name from wither it came. It is only a value. 

Of course, an implementation could use the notation `index(@)` to represent the index or name associated with `@`, but it would be an ad hoc thing, using information unavailable to your custom function, were it to be passed `@`.  

> Making this a parameterless function makes it hard for users to do things they're not allowed to do or don't make sense. It already knows that its context is the current item (and the item's parent).

In order for the function to "know" anything about its context, it needs to be passed a parameter (possibly hidden) such as "this" in C++ or "self" in Python, or otherwise bound to an environment. To support that would make a specification for functions much more complicated, certainly beyond that of [JMESPath functions](https://jmespath.org/specification.html#built-in-functions), for example.

**Comment by gregsdennis** [comment]
Firstly, we're not trying to build a full programming language.  If we were, I might be inclined to agree with you.  But we're trying to build a query syntax, and that affords us some liberties.

I think you're looking at it from a pure-functional point of view.  A pure function would, in most cases, return a constant without any parameters.  But as I said, we're not building a _programming_ language, functional or otherwise.

An example of a parameterless function (in another query language) would be SQL's `DATE()` function, which returns the current date.  It is _defined_ to have the context of the system on which the query is running.  It _never_ returns the same value twice (without adjusting the system or mocking that dependency entirely).

Similarly, the `index()` function could be _defined_ to have the context of the iterator in which it runs, i.e. the filter query `[?()]`.

Since you made a parallel with C++, consider this like a member function that's defined on the iterator itself rather than a static/global function.  Even if you consider `this` as a (hidden) parameter, it doesn't appear as a parameter when you call it ("hidden" 😉);  the parameter list is empty.

`length(x)` acts more like the pure function you're thinking of.  It doesn't need any context; it just acts on the parameter it's given.  But this doesn't mean that `index()` must also work that way.

Lastly, defining `index()` this way opens the door for others functions, and even user-defined functions if we do that, to do similar things, which I think it's extremely useful.  Requiring only pure functions severely inhibits their usefulness.

**Comment by danielaparker** [comment]
> Similarly, the index() function could be defined to have the context of the iterator in which it runs, i.e. the filter query [?()].

Okay, I've changed my mind about that, and agree. It's analogous to the XPath `fn:position()` function. I think you'd want separate functions for returning the index for an array and the name for an object member, though.

**Comment by cabo** [comment]
Will be covered with #203
