### ISSUE TITLE
"Union" could have more description, and maybe a new name

### ISSUE THREAD

**Issue by gregsdennis** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#21]
The term "union" will likely be unfamiliar for readers (it is for me) and could use a bit more description than "A union ~matcher~ selector consists of one or more union elements."

"Union" isn't a common term outside of set manipulation.  I would call the `[...]` an "indexer," which is a much more well-known term and is already associated with this construct in many programming languages.  The values inside are indices (as opposed to "union children" or "union elements"), of which there are multiple types:

- Integer
- Slice
- String
- Container query expression
- Item query expression

See [selector query expressions](https://github.com/jsonpath-standard/internet-draft/issues/17) for more details on the query-style indexers.

**Comment by glyn** [comment]
Good point. We have yet to decide whether unions remove or preserve duplicates and I think the outcome of that decision should influence the naming. "Union" as you point out has a set theory connotation and implies removing duplicates. It's tricky though because I think the result is ordered, whereas sets aren't ordered.

**Comment by gregsdennis** [comment]
Regarding duplicates specifically, please see #23.

**Comment by cabo** [comment]
Not much actionable discussion here.
Confirm no change needed at 2022-01-18 interim.
