### ISSUE TITLE
descendant selector non-determinism

### ISSUE THREAD

**Issue by glyn** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#215]
Currently, the descendant selector spec allows some non-determinism which may be unexpected.

The spec currently says that in the resultant nodelist from the descendant selector:
* nodes occur before their children, and
* nodes of an array occur in array order.

This sometimes allows multiple orderings when the result includes children of a node, but not the node itself.

For example, with the document:
```
[0, [1]]
```
the selector `$..[0]` could, according to the spec, produce the nodelist:
```
[0, 1]
```
or the nodelist:
```
[1, 0]
```

This is surprising given that there are no objects in the document, since object ordering is the usual source of non-determinism.

We could change the spec to constrain the order of traversal rather than the order of the resultant nodelist, but this seems to be getting into implementation detail.

Is the current approach acceptable?

**Comment by glyn** [comment]
> Have I missed something? Is it a matter of updating the semantics to say the entirety of the current node is looked at first?

I think something like that is probably desirable, but without unduly constraining implementations.

> (Side note - the spec is not as clear on the element-index only applying to arrays. It's implied, but not stated as clearly as it is for quoted-member-names and objects.)

Thanks. I'll take a look at that with an editorial PR.

**Comment by glyn** [comment]
I think rewording the second condition ("nodes of an array occur in array order") achieves the desired ordering:
* nodes of a given array, and descendants of nodes of the given array, occur in array order.

**Comment by gregsdennis** [comment]
> I don't see how the result could be `[1,0]`.

I'm still here. I'm not sure that anything needs to be updated. I think the current text (node then descendants) is sufficient to guarantee the correct ordering.

In this case,

- `[0, [1]]` is processed, producing `0`
- then `[1]` is processed, producing `1`

It must be this way because of array ordering.

`..` gives the (ordered) node list `[ [0,[1]], 0, [1], 1 ]`.  Of those, we take the first elements of arrays, which is `0` from `[0,[1]]` and `1` from `[1]`.  I'm really struggling to see how the current wording can yield anything else.

**Comment by glyn** [comment]
The behaviour of [four existing implementations](https://jsonpath.herokuapp.com/) is interesting. With the document:
```
[["b"], ["c"]]
```
and the selector `$..*`, Nebhale produces a result obeying the reworded conditions (but starts the nodelist with `$`):
```
[
   [
      [
         "b"
      ],
      [
         "c"
      ]
   ],
   [
      "b"
   ],
   "b",
   [
      "c"
   ],
   "c"
]
```
Jayway and Goessner place `"b"` after `["c"]`, contrary to the reworded conditions:
```
[
   [
      "b"
   ],
   [
      "c"
   ],
   "b",
   "c"
]
```
and Gatling doesn't even get close to the spec:
```
[
   [
      [
         "b"
      ],
      [
         "c"
      ]
   ]
]
```

**Comment by glyn** [comment]
> > I don't see how the result could be `[1,0]`.
> 
> I'm still here. I'm not sure that anything needs to be updated. I think the current text (node then descendants) is sufficient to guarantee the correct ordering.
> 
> In this case,
> 
>     * `[0, [1]]` is processed, producing `0`
> 
>     * then `[1]` is processed, producing `1`
> 
> 
> It must be this way because of array ordering.
> 
> `..` gives the (ordered) node list `[ [0,[1]], 0, [1], 1 ]`. Of those, we take the first elements of arrays, which is `0` from `[0,[1]]` and `1` from `[1]`. I'm really struggling to see how the current wording can yield anything else.

The problem with the current wording is that it allows too much freedom in the resultant nodelist. The result `[1, 0]` is allowed because:

*    nodes occur before their children (since `0` isn't a child of `1` or vice versa), and
*    nodes of an array occur in array order (since `0` and `1` are not nodes of the same array).

I think you are interpreting `..*` differently from the spec. You are regarding it as a combination of `..` and `.*`, but there is no `..` selector _as such_ in our spec.

**Comment by cabo** [comment]
> The spec currently says that in the resultant nodelist from the descendant selector:
> 
> * nodes occur before their children, and
> * nodes of an array occur in array order.

It probably should say that this is the node order of the node list that describes the entire input JSON value.

A node list is a subset of that novelist, preserving order.

**Comment by glyn** [comment]
> > The spec currently says that in the resultant nodelist from the descendant selector:
> > 
> > * nodes occur before their children, and
> > * nodes of an array occur in array order.
> 
> It probably should say that this is the node order of the node list that describes the entire input JSON value.

Hmmm. That's a bit tricky because there isn't necessarily a unique node order (because objects are not ordered). So, at best, it describes a collection of ordered nodelists and then the resultant nodelist is a subset of any one of those nodelists, preserving order.

> 
> A node list is a subset of that novelist, preserving order.

I think the reworded condition above captures the constraint more simply.

**Comment by gregsdennis** [comment]
> - nodes occur before their children, and
> - nodes of an array occur in array order.

These rules necessitate that 0 come before 1 in the above case.

Let's look at the `[["b"], ["c"]]` case because it's more interesting given the array as the first item.

Evaluating the array in sequence and nodes before children has two possible processes:

1. Evaluate each item, evaluating its children before moving to the next item.
    - Order of processing is `[["a"],["b"]]`, `["a"]`, `"a"`, `["b"]`, `"b"`.
2. Queue each item, queuing its children as the item is processed, eventually running through the queue.
    - Order of processing is `[["a"],["b"]]`, `["a"]`, `["b"]`, `"a"`, `"b"`.

In both cases, the resulting node list is `[ ["a"], "a", "b" ]`.  You _never_ get `"a"` before `"b"`, which means that you will _always_ get `[ 0, 1 ]` in the first example.

The only question is whether `..` does 1 or 2 from above.

**Comment by glyn** [comment]
I would agree, if the spec required evaluating the array in sequence and nodes before children, but it doesn't. It only talks about the order of the resultant nodelist. What text in the spec makes you think it is talking about the order of evaluation, as such?

Of course, the order of the resultant nodelist _implies_ some things about the order of evaluation, but it doesn't say anything about the ordering of nodes relative to the descendants of their siblings.

**Comment by gregsdennis** [comment]
> if the spec required evaluating the array in sequence and nodes before children,

I thought we already defined this.  I'll need to consult the spec again.

**Comment by graza** [comment]
Perhaps the others also did what I did and treated the `..` and what follows as two separate steps?  The descendant part only visits each of the nodes leaving it to the second part to process what's there.  This allows the same code to be used as for the non-descendant version of the same selector.  (It also means that my descendant selector allows list selectors because I removed the other types of selectors in favour of that.)

If `..*` is a single step and takes care of both jobs, descending and wildcard, then I could see how the following alternate result could be returned:

```json
[
    [ 0 ],
    0
    [ 1 ],
    1
]
```

The definitions at the top of this JSONPath document mentions a "transitive closure over the chidlren relation" but that was too mathematical for me.

I had a look at XPath's descendant-or-self but the spec didn't tell me exactly what to expect.  I tried the following XML using an [online XPath tester](https://www.freeformatter.com/xpath-tester.html):

```xml
<arr>
  <el>
    <arr>
      <el>0</el>
    </arr>
  </el>
  <el>
    <arr>
      <el>1</el>
    </arr>
  </el>
</arr>
```

An XPath of `//el` produced something like the "alternate result" I've given above:

```
Element='<el>
   <arr>
      <el>0</el>
   </arr>
</el>'
Element='<el>0</el>'
Element='<el>
   <arr>
      <el>1</el>
   </arr>
</el>'
Element='<el>1</el>'
```

**Comment by gregsdennis** [comment]
> Perhaps the others also did what I did and treated the .. and what follows as two separate steps?

Yes, that's what I've done in my implementation as well.

But in terms of the specification, `..` must always be coupled with another selector, whether that's a name, wildcard, or bracket-syntax.  As such it makes sense to define it in conjunction with the "second" selector.

There's some discussion [in the PR](https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/pull/218#discussion_r915490072) as well.

**Comment by cabo** [comment]
> On 6. Jul 2022, at 08:32, Glyn Normington ***@***.***> wrote:
> 
> 
> The spec currently says that in the resultant nodelist from the descendant selector:
> 
> 	• nodes occur before their children, and
> 	• nodes of an array occur in array order.
> It probably should say that this is the node order of the node list that describes the entire input JSON value.
> 
> Hmmm. That's a bit tricky because there isn't necessarily a unique node order (because objects are not ordered). So, at best, it describes a collection of ordered nodelists and then the resultant nodelist is a subset of any one of those nodelists, preserving order.

All the spec needs to require is that there is an input order that the output nodelist is a subsequence of.

> A node list is a subset of that novelist, preserving order.
> 
> I think the reworded condition above captures the constraint more simply.

After you have banged it into shape to actually do this, I’m not so sure…

Grüße, Carsten

**Comment by glyn** [comment]
> All the spec needs to require is that there is an input order that the output nodelist is a subsequence of.

That would work, but we'd need to define "input order" carefully as it's not necessarily unique because of objects.

**Comment by glyn** [comment]
@cabo I had a go at the "input order" approach. See the [additional commit](https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/pull/218/commits/b627cdf4da8968f871420dc1b878a2a69265584a) in PR 218.

**Comment by cabo** [comment]
Great.  Maybe we should give orders that satisfy the criteria a name; with your text, maybe "visit order"?

**Comment by glyn** [comment]
> Great. Maybe we should give orders that satisfy the criteria a name; with your text, maybe "visit order"?

Happy to attempt something once https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/pull/220 lands. I feel that "visit order" is a little too generic. I would prefer a more specific term such as "array preorder". WDYT?

(Happy to continue this thread here, but feel free to move to a fresh editorial issue if you prefer.)
