### ISSUE TITLE
Clarify that nested filter expressions are supported

### ISSUE THREAD

**Issue by glyn** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#340]
This needs emphasising in the spec.

**Comment by gregsdennis** [comment]
This feature raises an interesting question about the meaning and scope of `@`.

```
$[?@.foo[?@.bar==42]]
```

- What is the scope of `@.bar` here?
- How would one reference the target item of the outer filter from the inner (analogous to using `$` in a filter)?

In this example it seems pretty clear to me, a human, that the user is wanting items that contain a `foo` property which themselves contain a `bar` property that equals 42.

While the above path isn't incorrect, perhaps it would be beneficial to steer the user to something more like

```
$[?@.foo.bar==42]
```

which accomplishes the same thing.

... In writing this comment, I'm struggling to devise/contrive examples where nested filters would be necessary; that is, examples of paths such that they can't be rewritten without need filters. If this is indeed the case, that paths with nested filters can be rewritten without nested filters, then do we really need to support nested filters?

**Comment by cabo** [comment]
```
$[?@.foo[?!@.bar]]
```

**Comment by goessner** [comment]
```$[?@.foo[?@.bar==42]]```

If `@.foo` itself is a container, you might want to iterate over its content and test if any member/element fulfills the given condition. In case of `true` the outer `@` is returned as a node(list). In case of false or if  `@.foo` is no container, `false` is returned. I cannot see, how to manage cases like that without nesting.

**Comment by goessner** [comment]
@gregsdennis,

`$[?@.foo.bar==42]` cannot be equivalent to `$[?@.foo[?@.bar==42]]`.

`$[?@.foo.x.bar==42]` or `$[?@.foo[5].bar==42]` could. But then you need to know about the `x` or the `[5]` ...

**Comment by gregsdennis** [comment]
Okay if everyone seems to agree that this syntax is necessary, then we need to deal with the scoping issues of `@`.

**Comment by glyn** [comment]
I think it's sufficient if @ binds to the innermost filter expression
enclosing the @. Are there any compelling reasons to go beyond that? I am
not aware of any implementations that go beyond that.

**Comment by gregsdennis** [comment]
>  I am not aware of any implementations that go beyond that.

That's probably because only having a single symbol for inner scopes (`@`) only affords access to the innermost scope.

> Are there any compelling reasons to go beyond that?

I would say the same reason one would include a `$`-rooted path in a filter: comparing something in the inner scope to something in an outer scope.

---

I wonder if a way to resolve this is to support repeated `@` symbols.  The number of `@`s indicate the scope.

```
$[?@.foo[?@@.bar==42]]
```

Something like this was recently adopted in [raw string literals](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/strings/#raw-string-literals) in c# 11.

With this approach, you can identify any level of scope in any depth of nesting.  Additionally, I think the occasion to need nested filters will be sufficiently uncommon that this syntax shouldn't be a burden on users.

**Comment by goessner** [comment]
Interesting ... if we want to compare something in the inner scope level to something in its parent level (or somewhere above) we may want to write via level numbering

```$[?@0.foo[?@1.bar==@0.baz]]```

Then, can we do an equivalent query 

```$[?@.baz == @.foo[?@.bar]]```

without level numbering? No, because `[?@.bar]` always results in a Boolean (existence test). But then

```$[?@.baz == @.foo.*.bar]```

also won't work with not a singular path on the right side of the comparison. Any idea?

**Comment by glyn** [comment]
I personally don't think that repeated @'s would pull their weight. In other words, I think the additional complexity in the spec (and implementations) would not be warranted by the usefulness of the feature.

But, given that such a feature is outside our charter and it could be added later, I think we should defer it.

**Comment by goessner** [comment]
Hmm ... perhaps 

```$[?@.baz == @.foo[?].bar]```

might be a solution without adding new syntax elements. Only `[?]`  must get a special meaning (we need to specify that case anyway, we didn't so far). Proposal:

`[?]` iterates over an object or array and directly returns the corresponding member/element value.

Apart from that I aggree to Glyn.

**Comment by goessner** [comment]
Btw., using this nice feature the  filter solution of the recent user inquiry

```$.building[?(@.floor[?(@.lift=="working" || @.apartment[?(@.rooms==1)])])]```

could be simplified to a nesting free version.

```$.building[?@.floor[?].lift=="working" || @.floor[?].apartment[?].rooms==1)]```

Need to think about consequences.

**Comment by gregsdennis** [comment]
I like the `@`-number solution as it's more terse.  I'm not sure what the `[?]` is supposed to do, though.

Regardless, I'm happy to defer so long as we forbid nested queries for now.  (If nested queries are supported currently, it should be removed or language added to forbid them.)

**Comment by goessner** [comment]
As I proposed:

> `[?]` iterates over an object or array and directly returns the corresponding member/element value.

I am confident that with it nesting support isn't necessary any more, as

```$[?@[?@<expression>]```

can be rewritten as

```$[?@[?]<expression>]```

**Comment by gregsdennis** [comment]
I'm sorry, I still don't understand the mechanics of that.  

How would you handle two nesting levels, each with an expression?  I think nesting is required to handle some of the more complex scenarios.

**Comment by goessner** [comment]
Here is an example. Given the argument

```{ "a":[1,2,3], "b":[3,4,5]}```

and the query

```$[?@[?@==3]]`` 

would result in the nodelist `["$['a']","$['b']"]`.
We could also  iterate by hand (0..2) and write

```$[?@[0]==3 || @[1]==3 || @[2]==3]```

or we can leave it to new value returning iterator `[?]` 

```$[?@[?]==3```

We might read that in English:

For each member value of the argument, does **any** element of it has value `3` ?

In the same way as `[*]` is called `all`, `[?]` might be called `any`.

**Comment by glyn** [comment]
Doesn't `@[?]==3` get us into the territory of comparing non-singular
paths, that we have so far avoided?

**Comment by goessner** [comment]
No ... since we should define `any` in the sense of: "the first match wins".

**Comment by cabo** [comment]
I don't know whether I understand the proposal for `[?]`, but it seems to me that this leads to a completely incompatible execution model based on backtracking.  Too much invention for me.

**Comment by goessner** [comment]
I don't know what you mean by backtracking. We do not deal with regular expressions here. So

```$[?@[?@==3]]```

might be represented by two nested loops (where comparisons are done in the inner one). Whereas 

```$[?@[?]==3]```

is also represented by two nested loops, where comparisons are always done in the outer one.

**Comment by brunerd** [comment]
Chiming in to say the scope of `@` strikes me the way it does @glyn, it would correlate to the innermost filter expression, nothing more complicated than that. The `@@` and `@0` syntax seem a bit more complex than needed? Rather than being able to "move up" in a query, structure it to descend **down** instead.

The example query from Bojan had these requirements (with some clarification).
Get buildings that have:
* A "floor" where the lift is "working" (lift=="working")
**AND** 
* An "apartment" where rooms equals 1 (rooms==1)

The query Stefan sent back used OR but I think AND is what's required:
`$.building[?(@.floor[?(@.lift=="working" && @.apartment[?(@.rooms==1)])])]`

If **wildcards** were allow couldn't it also be expressed like this? 
`$.building[?(@.floor.*.apartment.*.rooms == 1 && @.floor.*.lift == "working")]`

Wondering why is a new `[?]` operator is needed when the `*` wildcard operator exists?

If neither wildcards nor nesting were allowed, one would need to find the intersection between these two discrete queries: `$.building.*.floor.*.apartment[?(@.rooms==1)]` and `$.building.*.floor[?(@.lift=="working")]`

Bojan expressed it in long form: 
`$.building[?(((@.floor[0].apartment[0].rooms==1||@.floor[0].apartment[1].rooms==1) && @.floor[0].lift=="working") || ((@.floor[1].apartment[0].rooms==1||@.floor[1].apartment[1].rooms==1) && @.floor[1].lift=="working"))]`

The path returned being: `$["building"][1]`

I have mostly come around to nested filters being a good thing, I wonder if it opens JSONPath up to attacks that "attempt to trigger unusually expensive runtime performance"  mentioned in section 4.1? Maybe that's not the specs "problem" but between this and `==` now operating on objects and arrays, avenues are being opening up to allow for "expensive" attacks where limitations previously precluded them.

Example data from Bojan for posterity:
```
{
   "building":
   [
     {
       "name":"Babbage",
       "floor":
       [
         {
           "level":1,
           "apartment": [ {"rooms":2}, {"rooms":3} ],
           "lift":"working"
         },
         {
           "level":2,
           "apartment":[ {"rooms":1}, {"rooms":4}],
           "lift":"not working"
         }
       ]
     },
     {
       "name":"Charles",
       "floor":
       [
         {
           "level":1,
           "lift":"notinstalled",
           "apartment": [ {"rooms":1}, {"rooms":2} ]
         },
         {
           "level":2,
           "lift":"working",
           "apartment": [ {"rooms":1}, {"rooms":4}]
         }
       ]
     }
   ]
}
```

**Comment by goessner** [comment]
@brunerd

You are right of course with *AND* ... my mistake.

`*` won't work with filters, since the spec requires singular pathes:

> Comparisons are restricted to Singular Path values, each of which selects at most one node, and primitive values (that is, numbers, strings, true, false, and null).

If we could somehow force the `*` returning a singular path inside of filters, this would be perfect.

**Comment by cabo** [comment]
2023-01-10 Interim: Do mention that nested filter expressions are allowed.
Do not try to address the scoping issue -- stick with $ and @ (innermost) only.

**Comment by gregsdennis** [comment]
I would like to propose a hybrid of the current definition of `@` and the `@1` approach that can be adopted later.

We could keep allowing `@` by itself with it's current meaning but also accept `@1` to specify a scope when necessary.  This would allow `@` in paths like

```
$[?@.foo[?@.bar==42]]
```

to retain its meaning of innermost scope while still giving users flexibility to specify scope when they need it, like

```
$[?@.foo[?@.bar==@1.baz]]
```

(This example assumes 1-based scope indexing, so `@1` is the scope of the outer filter.)

***NOTE** This bears striking similarity to [Relative JSON Pointers](https://www.rfc-editor.org/rfc/rfc6901).*

**Comment by gregsdennis** [comment]
@glyn I'm merely continuing the conversation what spawned as a result of the topic of the issue: scoping.  Arguably, that's what this issue is really about (and why I asked for it to be opened).

It seems that the desire is to keep the current scoping rules, and that's fine, but I wanted to wrap up the current conversation with an idea that we can maintain the current rules _and_ adopt the new syntax for new scoping as well.

**Comment by cabo** [comment]
> **NOTE** This bears striking similarity to [Relative JSON Pointers](https://www.rfc-editor.org/rfc/rfc6901).

Yes, that is what made me weary here.
(We are very happy to have thrown out Relative JSON Pointers from SDF...
Let the computer do the counting.)

**Comment by gregsdennis** [comment]
> Let the computer do the counting.

I'd like to highlight a path that @goessner wrote as an example in #156:

```jsonpath
$[? index(@[? @ == 5]) == 'odd']
```

This path contains a nested scope, and while it's fine for a computer to read this, it's a bit uneasy on human eyes.  Understanding the differing scopes in `@[?@==5]` takes a few mental cycles.

I think this would be greatly clarified for human readers if we used the multi-`@` approach:

```jsonpath
$[? index(@[? @@ == 5]) == 'odd']
```

Here the scopes are easily identified.

**Comment by glyn** [comment]
I find `@@`( or `@2`) more difficult to understand. I think it would be tricky to define that syntax in ABNF too, because the syntax depends on the context.

**Comment by gregsdennis** [comment]
Personal preference, I guess, but I find it requires significantly more effort to mentally parse what each `@` means in `$[? index(@[? @ == 5]) == 'odd']`.

**Comment by goessner** [comment]
Some kind of syntax highlighting might help here in the future ...

![grafik](https://user-images.githubusercontent.com/4902746/215835239-3093d140-b6fd-4ec8-9e5d-84f896d73087.png)

**Comment by cabo** [comment]
> ![grafik](https://user-images.githubusercontent.com/4902746/215835239-3093d140-b6fd-4ec8-9e5d-84f896d73087.png)

Too bad that we can't do this in the RFC (which are essentially monochrome).

**Comment by gregsdennis** [comment]
The syntax highlighting is nice, but it's tooling-dependent, which doesn't really solve the problems of scope access or readability.
