### ISSUE TITLE
TestBoolean vs. JSONBoolean -- are they the same or different?

### ISSUE THREAD

**Issue by cabo** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#389]

**Comment by gregsdennis** [comment]
My argument for a distinction (related to #387).

When we first started discussing path expressions, we decided that `true` was disallowed in expressions.  This was intended to disambiguate `$[?@.a]` from being either an existence test or a check that the value in `@.a` is `true` (e.g. `[{"a": true}]`).  As a result of this decision, the literal `true` was only valid as a `comparable`; that is, it can only be used with a comparison operator, and a path such as `$[?1==1 && true]` is syntactically invalid.

This means that there must be some distinction between the result of `1==1` and the literal `true`, although the colloquial meaning for both is "true."

---

In the interim call, I gave the example that if these are the same, then `(1==1)==(1==2)` should be valid.  Here's why.

If `1==1` is the same thing as the literal `true`, then I can do substitution and a valid expression should result.

```
(1==1)==(1==2)
true==(1==2)
true==false
```

Since `true==false` is a valid expression, it is implied that `(1==1)==(1==2)` is a valid expression by substituting back the other way.  But the ABNF forbids such an expression, so we have a contradiction, which implies our original assumption ("`1==1` is the same thing as the literal `true`") must have been wrong.

---

Pedantically, the literal `true` is just that: a literal.  It's no different than the literal `null`.  It shouldn't carry any meaning of truthiness behind it, but it is commonly used that way.

In terms of our expressions, it should be used as a mere token.  `@.a == true` is asking if the value in `@.a` is the JSON token `true`.  The comparison returns a "true" or "false" result, an actual boolean value rather than just the JSON `true` token, which can then be

- interpreted as the final result of the expression, or
- used as an operand for a logical operator, which itself returns a boolean to be interpreted as the final result of the expression.

**Comment by gregsdennis** [comment]
I also want to explore the idea of "lowering" a TestBoolean to a JSONBoolean so that it can be used in a comparison.

This idea is that we can go from a TestBoolean "true"/"false" to the JSONBoolean `true`/`false`, respectively, but not the other direction.

This does retrict the literals `true` and `false` from being used in a logical expression (e.g. `@.a && true`).  However, if TestBoolean can be lowered to function as JSONBoolean, then `(1==1)` can be lowered to `true` and `(1==2)` can be lowered to `false`, still implying that `(1==1)==(1==2)` is valid.

I think the only recourse here is to keep them distinct ideas.

**Comment by glyn** [comment]
I agree there should be a clear distinction between JSON booleans and the truth values associated with `comparison-expr` and `test-expr`. I believe the WG consensus supports this, as does the spec.

**Comment by gregsdennis** [comment]
> I agree there should be a clear distinction between JSON booleans and the truth values associated with `comparison-expr` and `test-expr`. - @glyn 

Good.  Progress.

> I believe the WG consensus supports this, as does the spec.

No.  The spec does not support this.  The spec says that a function which returns `OptionalBooleanType` can be used in both `comparison-expr` and `test-expr`.  But you just said above that there needs to be a distinction between these.

See my response to @cabo in https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/387#issuecomment-1424813328 as to why `OptionalBooleanType` cannot represent JSON booleans.  I don't feel like making that argument again.

**Comment by cabo** [comment]
(Please also see the discussion in #394 and #393, which is quite useful to find the root cause of this disagreement.)
