### ISSUE TITLE
Filter applied to JSON object: to support, or not to support?

### ISSUE THREAD

**Issue by danielaparker** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#47]
Should JSONPath filters apply to both JSON objects and arrays, or only to JSON arrays? 

In [JSONPath Comparison](https://cburgmer.github.io/json-path-comparison/results/filter_expression_on_object.html) , where the JSONPath expression 

    $[?(@.key)]

 is applied to the JSON instance 

    {"key": 42, "another": {"key": 1}}

there is no consensus. Thirteen implementations produce

    [ { "key": 1}]   (*)

Nine (including the important Jayway) produce

    [ { "another": { "key":1}, "key": 42 }]   (**)

Two (including JavaScript Goessner) produce

    [ 42, { "key": 1 }]   (***)

The remaining 17 (including PHP Goessner) produce variously `[]`, "syntax error", "not supported", or runtime error.

Results (`*`), (`**`) and (`***`) have implications for what the symbol `@` for the "current item" must mean.

For (`*`),  the value part of each name-value pair is evaluated in succession, and the value part being evaluated is represented by the symbol `@`.

For (`**`) , the JSON object that the filter is applied to is evaluated, the JSON object _is_ the current item, and there is no other. There can be only one current object, and it is either selected or not.

I can't make any sense of (`***`).

Intuitively, if I had a huge JSON object, I might want to filter out a subset of name-value pairs, and box them in a smaller JSON object, but none of the implementations support that notion.

**Comment by glyn** [comment]
I would prefer not to support (usefully) applying filters to JSON objects. For consistency with other cases, such as arraying indexing or slicing applied to a JSON object, I think the result should be an empty list of values rather than an error.

My reasoning is to try to keep JSONPath intuitive. The above variation in behaviour between the various implementations seems to be evidence that there isn't an intuitively obvious specification for this behaviour.

**Comment by gregsdennis** [comment]
I wouldn't mind including objects, but I'd definitely prefer option 1 (`*`).  I can see value in having it.

I think the wording I'd use for this in the specification would be "SHOULD NOT evaluate objects" so that is obvious the specification recommends against it, but still leaves it open for implementations to support it.  I'd probably go so far as to include something like "such functionality MUST be behind an option that defaults to 'not supported.'"  (See similar wording for JSON Schema's [`format` keyword in draft 2020-12](https://datatracker.ietf.org/doc/draft-bhutton-json-schema-validation/?include_text=1), section 7.2.1, paragraph 2.)
