### ISSUE TITLE
Saved issues link 404

### ISSUE THREAD

**Issue by akirataguchi115** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#476]
The 'saved issues' link gives one 404 when one navigates here in the GitHub Pages deployment: https://ietf-wg-jsonpath.github.io/draft-ietf-jsonpath-base/fix-470/ .

**Comment by cabo** [comment]
Right.  I'm not sure we have set up the CI here correctly.  This is not a practical problem, as you can always use the "issues" link instead -- "saved issues" is mostly useful when GitHub is broken.

**Comment by akirataguchi115** [comment]
Has there been a time when GitHub has been broken? Doesn't "saved issues" just redirect back to GitHub?

**Comment by cabo** [comment]
On 9. Jun 2023, at 12:59, Akira Taguchi ***@***.***> wrote:
> 
> 
> Has there been a time when GitHub has been broken?
> 
Yes, but only briefly.

We have these issue saving processes to have some minimal backup in the repos for information that is only on GitHub (the git repos themselves are mirrored by enough people that the information is unlikely to be lost).

Since we don’t have control over the business practices of GitHub, we need to be prepared for contingencies (e.g., deliberate business discontinuation or imposition of unacceptable rules, bankruptcy, legal issues, etc.).
> Doesn't "saved issues" just redirect back to GitHub?
> 

Yes, so you can easily check what has actually been saved (and we seem to see that the process is currently broken in this GitHub repo).

The recovery process that we’ll use in contingencies of course can’t use the existing GitHub workflows, so some assembly will be required — but at least we limit the information loss.

Grüße, Carsten

**Comment by cabo** [comment]
https://ietf-wg-jsonpath.github.io/draft-ietf-jsonpath-base/issues.html now seems to be populated, so I'm closing this issue.  Thank you!

**Comment by akirataguchi115** [comment]
https://ietf-wg-jsonpath.github.io/draft-ietf-jsonpath-base/fix-470/issues.html still gives my 404.

**Comment by cabo** [comment]
Interesting.  I believe this is a bug in the scripts setting up these branch-specific index.html files.
