### ISSUE TITLE
Respect Implementations

### ISSUE THREAD

**Issue by fiestajetsam** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#63]
(This was original raised in #54 and now being split out)

> As I mentioned in the session, I think there's a non-trivial amount of risk here that some implementations won't be willing or able to move away from their current behaviours, even if interoperability would improve if they did so. However, there are ways to mitigate that (e.g., a separate 'rfcxxxx compliant' mode). Even so, it will be important to get good participation from as many current implementers as possible.
*(Mark Nottingham)*

> The WG will develop a standards-track JSONPath specification that
is technically sound and complete, based on the common semantics
and other aspects of existing implementations.  Where there are
differences, the working group will analyze those differences and
make choices that rough consensus considers technically best, with
an aim toward minimizing disruption among the different JSONPath
implementations.
*(Barry Leiba)*

> I'm OK with this, but for context: I've been a pretty intense JSONPath user
in recent years, and AFAIK the spec, and the implementations, are mostly
OK, so the choice between "make JSONPath good" and "don't invalidate
implementations" is unlikely to come up. If it did, my predisposition would
be to err on the side of not breaking implementations, but I don't think
that's inconsistent with Barry's text.
*(Tim Bray)*

**Comment by danielaparker** [comment]
> "I've been a pretty intense JSONPath user in recent years, and AFAIK the spec, and the implementations, are mostly OK, so the choice between "make JSONPath good" and "don't invalidate implementations" is unlikely to come up. If it did, my predisposition would be to err on the side of not breaking implementations".
>
> Tim Bray

I think this may be a somewhat sanguine view. [The data](https://cburgmer.github.io/json-path-comparison/) suggests that while there is consensus on some points, there is division on others. Some differences reflect basic differences between two of the earliest and most influential implementations, Goessner Javascript, and [Jayway Java](https://github.com/json-path/JsonPath). For example, Jayway is an outlier when it comes to the meaning of [a filter applied to a JSON object](https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-jsonpath/issues/47), but what an outlier! As [@bettio has noted](https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-jsonpath/issues/59#issuecomment-801315787), the GitHub site has 5.7k stars, 1.1k forks, 50 contributors and is used by 1236 artifacts on maven, not to mention it's [Oracle's JSONPath](https://docs.oracle.com/cd/E60058_01/PDF/8.0.8.x/8.0.8.0.0/PMF_HTML/index.htm#t=JsonPath_Expressions.htm). And Jayway users really like what happens when they apply a filter to a JSON object, see e.g. [here](https://github.com/dchester/jsonpath/issues/86#issuecomment-572055012).

Then there is the [issue of whether to allow dash characters in unquoted names](https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-jsonpath/issues/16). Most legacy implementations [support a dash in the path](https://cburgmer.github.io/json-path-comparison/results/dot_notation_with_dash.html), as in
```
$.key-dash
```
but most [do not support a dash in filter predicates](https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_dot_notation_with_dash.html), as in
```
$[?(@.key-dash == 'value')]
```
Will the WG accept a specification with different naming conventions for the path and for the filter predicate? It seems unclean. But when you put your hands into "the current physical tarpit", you don't come out with clean hands, you come out with tar on your hands.

The issue with dash characters portends a bigger difference, between the implementations such as Goessner that use an interpreted language for evaluating expressions, and those such as Jayway that specify an evaluation syntax for evaluating expressions. Here, the differences are great. For example, there are big differences in the evaluation of an expression with comparators between the Javascript and PHP implementations, and many of the others. See e.g. [here](https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_boolean_or_operator_and_value_false.html) and [here](https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_boolean_or_operator_and_value_true.html). These differences have to do with type rules, whether for example the ">" comparator applies to number types only, or all types. Javascript and PHP distinguish between "==" and "===", between comparison with type coercion, and strict comparison between values of the same type. Other implementations only have "==", and have a stricter notion of comparison. See e.g. [here](https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_equals.html) and [here](https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_triple_equal.html).

It seems to me that the goal of "not breaking implementations" is a pyrrhic one, in that it could only be accomplished by having so much latitude in the spec that it would defeat the purpose of having a spec. While the charter exists and cannot be changed, it can be interpreted. My inclination, particularly as we have Stephan Goessner among us, would be to interpret it to mean that we want to look at the original, stay consistent with its author's original vision, preserve its essential elements, but see how far we can take it by, on the one hand, generalizing its elements, and, on the other hand,  tightening for consistency and well defined type rules.

Realistically, legacy implementations with big userbases are not going to change regardless of what the IETF spec says. The Oracle JAVA implementation (which is Jayway) is unlikely to change. The new implementations, particularly the open source ones with smaller existing userbases, are the ones more likely to adopt the spec. Over time, you may see Oracle Java 2, in a different namespace, which also implements the spec. Perhaps in ten years, the spec will be widely adopted.

**Comment by cabo** [comment]
I expect the RFC will have the tar washed off.
(E.g., artifacts from specific scripting languages -- who needs those?)
This of course means that not all existing queries will work on all implementations of the standards.  
That should not come as a big surprise.

**Comment by danielaparker** [comment]
@cabo wrote:

> I expect the RFC will have the tar washed off.
> (E.g., artifacts from specific scripting languages -- who needs those?)
> This of course means that not all existing queries will work on all implementations of the standards.

Maybe. But I'm starting to become pessimistic that a "full standards" IETF RFC describing interoperable JSONPath implementations is likely to emerge from the WG. Even among the few participants that we have, there appear to be fundamentally different points of view about the nature and scope of the WG's mandate.

**Comment by cabo** [comment]
I don't know -- once the editors start to merge pull requests, and the chairs start to moderate the emerging progress, we might see the convergence materialize in the draft.

**Comment by gregsdennis** [comment]
> This of course means that not all existing queries will work on all implementations of the standards.

I'd be surprised if any one implementation actually fully complied with the forthcoming spec.  I expect to make changes.

**Comment by cabo** [comment]
This discussion led to better understanding of the objectives but does not seem to have actionable items left.
Closing.
