### ISSUE TITLE
Valid identifiers

### ISSUE THREAD

**Issue by bettio** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#9]
A valid identifier rule (for "dot child" and recursive descent) should be discussed.

* All implementations agree on `[a-zA-Z_][a-zA-Z0-9_]*`
* Most implementations allow a dash in the middle of a identifier (e.g. `key-dash`)
* Consensus on `$.-key` and `$.key-` has not been investigated
* Most implementations allow unicode identifiers such as `$.屬性`
* Consensus on digits as first identifier character has not been investigated

## Proposal
* Identifier regexp must be simple. e.g. some implementations allow any unicode codepoint except `\s`, `\t`, `$`, `.`, `*`, etc... This approach allows writing regexp similar to `[^'".*()$?,>=<\-\:\@\[\]\s\t\n\r]*`. If this approach is confirmed a list of disallowed codepoints should be identified.
* `-` should not be allowed as first identifier character
* `[0-9]` as first identifier character should be investigated and discussed.

**Comment by glyn** [comment]
I believe the context for this issue is "dot child" (e.g. `.somekey`) as union/bracket child should allow more esoteric possibilities (e.g. `[" "]`). Also, it may be relevant to (so called, currently) recursive descent (e.g. `..somekey`).

For consensus on digits as first identifier character, [dot_notation_with_number](https://cburgmer.github.io/json-path-comparison/results/dot_notation_with_number.html) and especially [dot_notation_with_number_object](https://cburgmer.github.io/json-path-comparison/results/dot_notation_with_number_on_object.html) are relevant.

@remorhaz is currently investigating the use of identifier syntax as part of https://github.com/jsonpath-standard/internet-draft/pull/5 and may wish to comment.

**Comment by bettio** [comment]
See also https://github.com/cburgmer/json-path-comparison/issues/42

**Comment by gregsdennis** [comment]
☝️ possible duplication

**Comment by danielaparker** [comment]
@bettio 

> A valid identifier rule (for "dot child" and recursive descent) should be discussed.
> 
> * Most implementations allow a dash in the middle of a identifier (e.g. `key-dash`)

It depends whether we're looking at the main path or in filter predicates.

In the main path, as in
```
$[?(@.key-dash == 'value')]
```
there is a [consensus to support a dash in identifiers](https://cburgmer.github.io/json-path-comparison/results/dot_notation_with_dash.html). However, in filter predicates, as in
```
$[?(@.key-dash == 'value')]
```
there is [no such consensus](https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_dot_notation_with_dash.html). Only 13 out of 41 implementations support a dash in identifiers in filter predicates.

**Comment by goessner** [comment]
I am more in the camp of the non-dash supporters ...

**Comment by cabo** [comment]
Closed in #102

**Comment by gregsdennis** [comment]
What was the resolution?  Do we allow hyphens?  Was a PR needed to change anything?
